services:
  server:
    build:
      context: .
    ports:
      - "8080:8080"
  
  db: 
    image: postgres
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data	
    env_file:
      - .env
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  
volumes:
  db-data: